--PHASE 1: CREATING TABLES
CREATE TABLE ADMINS (
ADMIN_ID NUMBER(5) NOT NULL, --PK
ADMIN_NAME VARCHAR2(40) NOT NULL,
ADMIN_EMAIL VARCHAR2(40) NOT NULL,
ADMIN_PASSWORD VARCHAR2(40) NOT NULL,
ADMIN_ROLE VARCHAR2(20) NOT NULL CHECK (ADMIN_ROLE IN ('SYSTEM_ADMIN', 'TEACHER')),
SYSTEM_ID NUMBER(5)--FK
);
CREATE TABLE SYSWEBPAGE (
SYSTEM_ID NUMBER(5), --PK
SYSTEM_URL VARCHAR2(40) NOT NULL
);
CREATE TABLE LECTURES (
LECTURE_ID NUMBER(10) NOT NULL, --PK,
LECTURE_NAME VARCHAR2(40) NOT NULL,
LECTURE_CLASS VARCHAR2(10) NOT NULL,
CREDITS NUMBER NOT NULL,
SYSTEM_ID NUMBER(5) --FK
);

CREATE TABLE EXAMINATIONS(
EXAM_ID NUMBER(10) NOT NULL, --PK
EXAM_NAME VARCHAR2(40) NOT NULL,
LECTURE_ID NUMBER(10) NOT NULL
);

CREATE TABLE STUDENTS(
STUDENT_ID NUMBER(20) NOT NULL, --PK
STUDENT_NAME VARCHAR2(40) NOT NULL,
STUDENT_EMAIL VARCHAR2(40) NOT NULL,
STUDENT_PASSWORD VARCHAR2(40) NOT NULL,
SYSTEM_ID NUMBER(5) --FK
);

CREATE TABLE GRADES(
GRADE NUMBER(3),
STUDENT_ID NUMBER(20) NOT NULL,--FK
LECTURE_ID NUMBER(10) NOT NULL
);

CREATE TABLE ATTEND(
EXAM_ATTENDING_DATE DATE NOT NULL,
STUDENT_ID NUMBER(20) NOT NULL, --FK
EXAM_ID NUMBER(10) NOT NULL --FK
); 

CREATE TABLE QUESTIONS(
QUESTION_ID NUMBER(20) NOT NULL,
QUESTION_TEXT VARCHAR2(999),
QUESTION_POINT NUMBER(2),
CORRECT_ANSWER VARCHAR2(50),
EXAM_ID NUMBER(10) NOT NULL --FK
);

CREATE TABLE ANSWER_OPTIONS(
A_ANSWER VARCHAR2(50),
B_ANSWER VARCHAR2(50),
C_ANSWER VARCHAR2(50),
D_ANSWER VARCHAR2(50),
E_ANSWER VARCHAR2(50),
QUESTION_ID NUMBER(20) NOT NULL
);


--PHASE 2: ADDING PRIMARY KEYS
ALTER TABLE ADMINS ADD(
CONSTRAINT ADMIN_PK PRIMARY KEY(ADMIN_ID)
);

ALTER TABLE SYSWEBPAGE ADD(
CONSTRAINT SYSTEM_PK PRIMARY KEY(SYSTEM_ID)
);

ALTER TABLE LECTURES ADD(
CONSTRAINT LECTURE_PK PRIMARY KEY(LECTURE_ID)
);

ALTER TABLE EXAMINATIONS ADD(
CONSTRAINT EXAM_PK PRIMARY KEY(EXAM_ID)
);

ALTER TABLE STUDENTS ADD(
CONSTRAINT STUDENTS_PK PRIMARY KEY(STUDENT_ID)
);

ALTER TABLE QUESTIONS ADD(
CONSTRAINT QUESTION_PK PRIMARY KEY(QUESTION_ID)
);

--PHASE 2: ADDING FOREIGN KEYS

ALTER TABLE ADMINS ADD(
CONSTRAINT ADMIN_SYSTEM_FK FOREIGN KEY(SYSTEM_ID) REFERENCES SYSWEBPAGE(SYSTEM_ID)
);

ALTER TABLE LECTURES ADD(
CONSTRAINT LECTURES_SYSTEM_FK FOREIGN KEY(SYSTEM_ID) REFERENCES SYSWEBPAGE(SYSTEM_ID)
);

ALTER TABLE STUDENTS ADD(
CONSTRAINT STUDENTS_SYSTEM_FK FOREIGN KEY(SYSTEM_ID) REFERENCES SYSWEBPAGE(SYSTEM_ID)
);

ALTER TABLE GRADES ADD(
CONSTRAINT STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
CONSTRAINT LECTURE_ID_FK FOREIGN KEY(LECTURE_ID) REFERENCES LECTURES(LECTURE_ID)
);

ALTER TABLE ATTEND ADD(
CONSTRAINT STUDENT_ATTENDING_FK FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
CONSTRAINT EXAM_ATTENDING_FK FOREIGN KEY(EXAM_ID) REFERENCES EXAMINATIONS(EXAM_ID)
);

ALTER TABLE EXAMINATIONS ADD(
CONSTRAINT LECTURE_EXAM_FK FOREIGN KEY(LECTURE_ID) REFERENCES LECTURES(LECTURE_ID)
);

ALTER TABLE QUESTIONS ADD(
CONSTRAINT EXAM_QUESTION_FK FOREIGN KEY(EXAM_ID) REFERENCES EXAMINATIONS(EXAM_ID)
);

ALTER TABLE ANSWER_OPTIONS ADD(
CONSTRAINT QUESTION_ANSWERS_FK FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID)
);
